// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128050719_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ChapterMissionCharacter", b =>
                {
                    b.Property<Guid>("ChapterMissionsChapterMissionID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharactersCharacterID")
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterMissionsChapterMissionID", "CharactersCharacterID");

                    b.HasIndex("CharactersCharacterID");

                    b.ToTable("ChapterMissionCharacter");
                });

            modelBuilder.Entity("Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumID");

                    b.HasIndex("GameID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Domain.Entities.ChapterMission", b =>
                {
                    b.Property<Guid>("ChapterMissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChapterMissionID");

                    b.HasIndex("GameID");

                    b.ToTable("ChapterMissions");
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterID");

                    b.HasIndex("GameID");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterID = new Guid("24bc0f9d-2749-40ac-bf17-14bcdd8a66eb"),
                            Description = "A witcher and the main protagonist of The Witcher series.",
                            GameID = new Guid("052b2a66-a6f6-4865-80bf-7b89175f79db"),
                            ImagePath = "",
                            Name = "Geralt of Rivia"
                        },
                        new
                        {
                            CharacterID = new Guid("3ad1890d-573b-44e6-ada2-268dfe65a569"),
                            Description = "The Child of Prophecy, a powerful source of Elder Blood.",
                            GameID = new Guid("052b2a66-a6f6-4865-80bf-7b89175f79db"),
                            ImagePath = "",
                            Name = "Ciri"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Entities.CompanyGame", b =>
                {
                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameID", "CompanyID", "Role");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyGames");
                });

            modelBuilder.Entity("Domain.Entities.Control", b =>
                {
                    b.Property<Guid>("ControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ControlID");

                    b.HasIndex("GameID");

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("Domain.Entities.DLC", b =>
                {
                    b.Property<Guid>("DLCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DLCID");

                    b.HasIndex("GameID");

                    b.ToTable("DLCs");
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualGameSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CriticsRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("GameDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameFiles")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursToComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkForCrack")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderOfFranchise")
                        .HasColumnType("TEXT");

                    b.Property<string>("PGRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patch")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerHours")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PlayersRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("SteamPrices")
                        .HasColumnType("Decimal(7,2)");

                    b.Property<string>("StoryPlace")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UserRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("YearOfRelease")
                        .HasColumnType("TEXT");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = new Guid("052b2a66-a6f6-4865-80bf-7b89175f79db"),
                            ActualGameSize = "57 GB",
                            CriticsRating = 9.6m,
                            GameDescription = "One of the most acclaimed RPGs of all time. Now ready for a new generation...",
                            GameEngine = "REDengine 3",
                            GameFiles = "",
                            GamePath = "D:\\SteamLibrary\\steamapps\\common\\The Witcher 3\\REDprelauncher.exe",
                            HoursToComplete = 174,
                            LinkForCrack = "",
                            Name = "The Witcher 3: Wild Hunt",
                            OrderOfFranchise = "3",
                            PGRating = "18 over",
                            Patch = "4.04",
                            PlayerHours = 60,
                            PlayersRating = 10m,
                            SteamPrices = 37.99m,
                            StoryPlace = "Temerian (southern) side of the Pontar in Velen",
                            UserRating = 10m,
                            YearOfRelease = "May 2015"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("MediaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MediaID");

                    b.HasIndex("GameID");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Domain.Entities.ModManager", b =>
                {
                    b.Property<Guid>("ModManagerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ModManagerID");

                    b.ToTable("ModManagers");
                });

            modelBuilder.Entity("Domain.Entities.Performance", b =>
                {
                    b.Property<Guid>("PerformanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageFPS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphicsQuality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Low1PercentFPS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxFPS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PerformanceID");

                    b.HasIndex("GameID");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("PlatformID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlatformID");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformID = new Guid("aff935b7-a122-45bf-b343-fb2b84ecfc47"),
                            Description = "Microsoft Windows operating system",
                            Name = "Windows"
                        },
                        new
                        {
                            PlatformID = new Guid("43b2427b-b32b-4a80-98c2-18b8c6f11934"),
                            Description = "Open-source operating system based on Unix",
                            Name = "Linux"
                        },
                        new
                        {
                            PlatformID = new Guid("59cfe7d1-6c6e-4d25-95b6-7c9f6b2f9245"),
                            Description = "Apple's operating system for Mac computers",
                            Name = "macOS"
                        },
                        new
                        {
                            PlatformID = new Guid("9af20714-09a5-4c83-9f6f-798dc91b1d02"),
                            Description = "Sony's gaming console platform",
                            Name = "PlayStation"
                        },
                        new
                        {
                            PlatformID = new Guid("4f46a6c9-1f94-4a63-9de8-2f85cbe5f05e"),
                            Description = "Microsoft's gaming console platform",
                            Name = "Xbox"
                        },
                        new
                        {
                            PlatformID = new Guid("77bba20d-79f2-4a89-9f60-10cc02c0f2cf"),
                            Description = "Nintendo's hybrid gaming console",
                            Name = "Nintendo Switch"
                        },
                        new
                        {
                            PlatformID = new Guid("e15e8ef7-8f6b-4e71-9f51-f8658d7f84d9"),
                            Description = "Google's mobile operating system",
                            Name = "Android"
                        },
                        new
                        {
                            PlatformID = new Guid("b5b8efb3-7f8d-48a3-88b7-6f1a9d85f5c7"),
                            Description = "Apple's mobile operating system",
                            Name = "iOS"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Requirement", b =>
                {
                    b.Property<Guid>("RequirementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectX")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Graphics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequirementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoundCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemOS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequirementID");

                    b.HasIndex("GameID");

                    b.ToTable("Requirements");
                });

            modelBuilder.Entity("Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("SongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlbumID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<Guid>("GamesGameID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenresGenreID")
                        .HasColumnType("TEXT");

                    b.HasKey("GamesGameID", "GenresGenreID");

                    b.HasIndex("GenresGenreID");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("GameModManager", b =>
                {
                    b.Property<Guid>("GamesGameID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModManagersModManagerID")
                        .HasColumnType("TEXT");

                    b.HasKey("GamesGameID", "ModManagersModManagerID");

                    b.HasIndex("ModManagersModManagerID");

                    b.ToTable("GameModManager");
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.Property<Guid>("GamesGameID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformsPlatformID")
                        .HasColumnType("TEXT");

                    b.HasKey("GamesGameID", "PlatformsPlatformID");

                    b.HasIndex("PlatformsPlatformID");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("ChapterMissionCharacter", b =>
                {
                    b.HasOne("Domain.Entities.ChapterMission", null)
                        .WithMany()
                        .HasForeignKey("ChapterMissionsChapterMissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Album", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Albums")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.ChapterMission", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("ChapterMissions")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Characters")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.CompanyGame", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany("CompanyGames")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("CompanyGames")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.Control", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Controls")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.DLC", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("DLCs")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.Media", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Medias")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.Performance", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Performances")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.Requirement", b =>
                {
                    b.HasOne("Domain.Entities.Game", "Game")
                        .WithMany("Requirements")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Domain.Entities.Song", b =>
                {
                    b.HasOne("Domain.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameModManager", b =>
                {
                    b.HasOne("Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ModManager", null)
                        .WithMany()
                        .HasForeignKey("ModManagersModManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatform", b =>
                {
                    b.HasOne("Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Platform", null)
                        .WithMany()
                        .HasForeignKey("PlatformsPlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyGames");
                });

            modelBuilder.Entity("Domain.Entities.Game", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ChapterMissions");

                    b.Navigation("Characters");

                    b.Navigation("CompanyGames");

                    b.Navigation("Controls");

                    b.Navigation("DLCs");

                    b.Navigation("Medias");

                    b.Navigation("Performances");

                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
